const featureCardsContent = [
  {
    url: "assets/icons/web/1.svg",
    title: "Search",
    text:
      "Simply add a keyword or a term related to your business in the slogan maker search box. Wait for the magic to happen."
  },
  {
    url: "assets/icons/web/2.svg",
    title: "Select",
    text:
      "Choose from thousands of options generated by the slogan maker that fit your needs."
  },
  {
    url: "assets/icons/web/3.svg",
    title: "Stand out",
    text: "Congrats on your new slogan. It's time to win the world!"
  }
];

/*
  Returns a feature card that has an image, title, and description.
*/

function Card({ feature }) {
  return (
    <div className="feature-card">
      <img
        className="feature-card-image"
        src={feature.url}
        alt={feature.title}
      ></img>
      <h3 className="feature-card-title">{feature.title}</h3>
      <p className="feature-card-text">{feature.text}</p>
    </div>
  );
}

/*
  Maps over the featureCardsContent array
  and generates feature cards for each entry.
*/
export default function Features() {
  return (
    <section className="features side-padding">
      {featureCardsContent.map((feature, i) => (
        <Card feature={feature} key={i} />
      ))}
    </section>
  );
}
